version: "3"
services:
  mysql:
    image: "mysql:5.7.10"
    container_name: "pf_db"
    ports:
      - "16720:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "portfolio"
    volumes:
      - pf_db:/var/lib/mysql
volumes:
  pf_db:
    driver: "local"
